- .github/workflows/sonar-push.yml
https://datical.atlassian.net/browse/DAT-13774
> DAT-13774 retrieve test results

- .github/workflows/create-release.yml
- .github/workflows/sonar-push.yml
https://datical.atlassian.net/browse/DAT-13774
> DAT-13774 retrieve artifacts before sonar

- .github/upload_asset.sh
- .github/workflows/extension-attach-artifact-release.yml
https://datical.atlassian.net/browse/DAT-13774
This pull request is addressing an issue related to how zip files are signed in extensions. The change is designed to handle zip files when they exist in the generated extension.
The problem arose when the current implementation failed to recognize the existence of zip files in extensions, leading to inconsistent results when attempting to sign them. With this pull request, we are introducing a new feature that will properly handle zip files and ensure that they are signed correctly.
The proposed change includes modifying the current implementation to identify zip files and apply the necessary steps to sign them.
> DAT-13774 sign zip files

- .github/workflows/create-release.yml
- .github/workflows/extension-attach-artifact-release.yml
- .github/workflows/extension-update-version.yml
- .github/workflows/os-extension-test.yml
- .github/workflows/pro-extension-test.yml
- README.md
- chore: update liquibase/build-logic to v0.3.2 in GitHub workflows
- feat: add extension-update-version.yml workflow to update release and development pom.xml versions using Maven release plugin
> DAT-15071 Automatically bump version for liquibase extensions

- .github/workflows/dependabot-automerge.yml
Add ability to automerge dependabot PRs for minor and patch dependencies only.
> Add dependabot automerge feature

- .github/workflows/create-release.yml
- .github/workflows/extension-attach-artifact-release.yml
- .github/workflows/extension-release-published.yml
- .github/workflows/os-extension-test.yml
- .github/workflows/pro-extension-test.yml
- README.md
https://datical.atlassian.net/browse/DAT-15565
chore(create-release.yml): update sonar-push.yml version to v0.3.6 fo…r the sonar job
chore(extension-attach-artifact-release.yml): update script file versions to v0.3.6 for get_draft_release.sh, sign_artifact.sh, and upload_asset.sh
chore(extension-release-published.yml): update extension-release-prepare.yml version to v0.3.6 for the maven-release job
chore(os-extension-test.yml): update sonar-pull-request.yml version to v0.3.6 for the sonar-pr job
chore(pro-extension-test.yml): update sonar-pull-request.yml version to v0.3.6 for the sonar-pr job
> DAT-15565 build-logic enhancement - move matrix to calling workflow

- .github/workflows/create-release.yml
- .github/workflows/extension-attach-artifact-release.yml
- .github/workflows/extension-release-published.yml
- .github/workflows/os-extension-test.yml
- .github/workflows/package-deb.yml
- .github/workflows/pro-extension-test.yml
do not require inputs for os and pro extension tests
> bugfix:  do not require input params for os and pro extension tests

- .github/workflows/extension-attach-artifact-release.yml
fix(extension-attach-artifact-release.yml): change assets pattern from "${{ env.artifact_id }}-*" to '*.*' to include all files as assets in the release
> DAT-12748 Reusable Workflows: Delete all artifacts from draft release when a new pr is pushed to main

- .github/workflows/create-release.yml
- .github/workflows/extension-attach-artifact-release.yml
- .github/workflows/extension-release-prepare.yml
- .github/workflows/extension-release-published.yml
- .github/workflows/extension-release-rollback.yml
- .github/workflows/os-extension-test.yml
- .github/workflows/package-deb.yml
- .github/workflows/pom-release-published.yml
- .github/workflows/pro-extension-test.yml
https://datical.atlassian.net/browse/DAT-15862
> DAT-15862 DevOps :: Release Rollback fails

- .github/workflows/extension-release-published.yml
in settings action instead of setup-java action due to overriding values
> bugfix: set sonatype staging server

- .github/release-drafter.yml
- .github/workflows/create-release.yml
- .github/workflows/extension-attach-artifact-release.yml
- .github/workflows/extension-release-prepare.yml
- .github/workflows/extension-release-published.yml
- .github/workflows/os-extension-test.yml
- .github/workflows/package-linux.yml
- .github/workflows/pom-release-published.yml
- .github/workflows/pro-extension-test.yml
https://datical.atlassian.net/browse/DAT-13175
> DAT-13175  Full automation of OSS extension release

- .github/workflows/create-release.yml
- .github/workflows/extension-attach-artifact-release.yml
- .github/workflows/extension-release-prepare.yml
- .github/workflows/extension-release-published.yml
- .github/workflows/os-extension-test.yml
- .github/workflows/package-linux.yml
- .github/workflows/pom-release-published.yml
- .github/workflows/pro-extension-test.yml
chore(create-release.yml): update version of sonar-push.yml to v0.6.0 for better compatibility
chore(extension-attach-artifact-release.yml): update version of scripts to v0.6.0 for better compatibility
chore(extension-release-prepare.yml): update version of extension-release-rollback.yml to v0.6.0 for better compatibility
chore(extension-release-published.yml): update version of extension-release-prepare.yml to v0.6.0 for better compatibility
chore(os-extension-test.yml): update version of sonar-pull-request.yml to v0.6.0 for better compatibility
chore(package-linux.yml): update version of scripts and package-deb-pom.xml to v0.6.0 for better compatibility
chore(pom-release-published.yml): update version of extension-release-prepare.yml to v0.6.0 for better compatibility …
> DAT-15738      DevOps: Refactor extensions upload xsds job to reusable workflows

- .github/workflows/create-release.yml
- .github/workflows/extension-attach-artifact-release.yml
- .github/workflows/extension-release-prepare.yml
- .github/workflows/extension-release-published.yml
- .github/workflows/os-extension-test.yml
- .github/workflows/package-linux.yml
- .github/workflows/pom-release-published.yml
- .github/workflows/pro-extension-test.yml
- chore(create-release.yml): update version of sonar-push.yml to v0.6.2 for better compatibility
- chore(extension-attach-artifact-release.yml): update version of get_draft_release.sh, sign_artifact.sh, and upload_asset.sh to v0.6.2 for better compatibility
- chore(extension-release-prepare.yml): update version of extension-release-rollback.yml to v0.6.2 for better compatibility
- chore(extension-release-published.yml): update version of extension-release-prepare.yml to v0.6.2 for better compatibility
- chore(os-extension-test.yml): update version of sonar-pull-request.yml to v0.6.2 for better compatibility
- chore(package-linux.yml): update version of package-deb-pom.xml and sign_artifact.sh to v0.6.2 for better compatibility
- chore(pom-release-published.yml): update version of …
> DAT-16579      DevOps :: Refactor liquibase-commercial-mongodb extension upload xsds job to reusable workflow

- .github/workflows/create-release.yml
- .github/workflows/extension-attach-artifact-release.yml
- .github/workflows/extension-release-prepare.yml
- .github/workflows/extension-release-published.yml
- .github/workflows/os-extension-test.yml
- .github/workflows/package.yml
- .github/workflows/pom-release-published.yml
- .github/workflows/pro-extension-test.yml
I created the branch from https://datical.atlassian.net/browse/DAT-4566 to prevent merge conflicts
> DAT-4565 Homebrew distribution

- .github/workflows/create-release.yml
- .github/workflows/extension-attach-artifact-release.yml
- .github/workflows/extension-release-prepare.yml
- .github/workflows/extension-release-published.yml
- .github/workflows/os-extension-test.yml
- .github/workflows/package.yml
- .github/workflows/pom-release-published.yml
- .github/workflows/pro-extension-test.yml
- README.md
- change all occurrences for 0.6.3 to 0.6.4 and update the README.md
feat : `.github/workflows/create-release.yml`
feat : `.github/workflows/extension-attach-artifact-release.yml`
feat: `.github/workflows/extension-release-prepare.yml
feat: `.github/workflows/extension-release-published.yml`
feat: `.github/workflows/os-extension-test.yml`
feat: `.github/workflows/package.yml`
feat: `.github/workflows/pom-release-published.yml`
feat: `.github/workflows/pro-extension-test.yml`
feat: `README.md`: update README.md for Releasing a new version of build-logic
> PREM-445: change all occurrences for 0.6.3 to 0.6.4 and update the README.md

- .github/workflows/create-release.yml
- .github/workflows/extension-attach-artifact-release.yml
- .github/workflows/extension-release-prepare.yml
- .github/workflows/extension-release-published.yml
- .github/workflows/os-extension-test.yml
- .github/workflows/package.yml
- .github/workflows/pom-release-published.yml
- .github/workflows/pro-extension-test.yml
- .github/workflows/sonar-jest-coverage.yml
- README.md
change all occurrences for 0.6.4 to 0.6.5 and update the README.md
feat : `.github/workflows/create-release.yml`
feat : `.github/workflows/extension-attach-artifact-release.yml`
feat: `.github/workflows/extension-release-prepare.yml feat: .github/workflows/extension-release-published.ymlfeat:.github/workflows/os-extension-test.yml`
feat: `.github/workflows/package.yml`
feat: `.github/workflows/pom-release-published.yml`
feat: `.github/workflows/pro-extension-test.yml`
feat: README.md: update README.md for Releasing a new version of build-logic
> PREM-445: sonar jest coverage logic change

- .github/workflows/create-release.yml
- .github/workflows/extension-attach-artifact-release.yml
- .github/workflows/extension-release-prepare.yml
- .github/workflows/extension-release-published.yml
- .github/workflows/fossa_ai.yml
- .github/workflows/os-extension-test.yml
- .github/workflows/pom-release-published.yml
- .github/workflows/pro-extension-test.yml
- README.md
ci(workflows): add support for specifying different Maven profiles in GitHub workflows
> DAT-17532  Allow obfuscation when using parent pom and reusable workflows

- .github/workflows/fossa_ai.yml
chore(fossa_ai.yml): reformat YAML file for better readability and consistency
> FIX: FOSSA project name

- .github/workflows/create-release.yml
- .github/workflows/extension-attach-artifact-release.yml
- .github/workflows/extension-release-prepare.yml
- .github/workflows/extension-release-published.yml
- .github/workflows/fossa_ai.yml
- .github/workflows/os-extension-test.yml
- .github/workflows/pom-release-published.yml
- .github/workflows/pro-extension-test.yml
- README.md
change all occurrences for 0.7.5 to 0.7.6 for the release
> change all occurrences for 0.7.5 to 0.7.6

- .github/workflows/ephemeral-cloud-infra.yml
🔧 (.github/workflows/ephemeral-cloud-infra.yml): pass github run id as a variable to terraform apply command
> DAT-17802  Change the ephemeral infra reusable workflow to use GH runID

- .github/workflows/owasp-scanner.yml
✨ (owasp-scanner.yml): add GitHub Actions workflow for OWASP Scanner to scan dependencies for security vulnerabilities and upload results as artifacts
> DAT-16650 Automate OWASP scanner- edit summary Automate OWASP scanner

- .github/workflows/slack-notification.yml
feat: `.github/workflows/slack-notification.yml` : slack notification with workflow_name
> DAT-17863: slack notification with workflow_file_name

- .github/workflows/pro-extension-test.yml
Without this fix we are running tests agains main branch and not the PR branch
> chore: test branch code when required

- .github/workflows/pro-extension-test.yml
issue : https://liquibase.slack.com/archives/C53DX4S4W/p1725463550524849?thread_ts=1725461124.310999&cid=C53DX4S4W
> Update pro-extension-test.yml to use shell bash

- .github/workflows/fossa.yml
feat: `.github/workflows/fossa.yml`: reusable workflow for Fossa report generation for Datical repositories
**NOTE**: Merge the PR after the report generation has been verified by the Enterprise team in jira ticket : https://datical.atlassian.net/browse/DAT-18147
> DAT-18147: Fossa report generation for Datical repositories

- .github/workflows/fossa.yml
Workflow_dispatch doesnt belong here. 
datical/build-logic -> triggers -> repository workflow -> triggers -> liquibase/build-logic -> runs the Fossa Analysis commands
> 🛠️ DAT-18147: fix the script

- .github/workflows/package.yml
🔧 (package.yml): refactor package.yml to move the file before running createrepo command to ensure the correct file is processed
> DAT-18783 RHEL package manager does not contain v4.29.2

- .github/workflows/package.yml
- fix: `.github/workflows/package.yml`: using GITHUB_OUTPUT instead of GITHUB_ENV to set true or false.
- Successful testing done here https://github.com/liquibase/liquibase/actions/runs/11728169581/job/32670952745
that  created automated PR:https://github.com/Homebrew/homebrew-core/pull/196986
> 🔧 DAT-19003:HomeBrew step fixes

- .github/workflows/fossa.yml
This pull request includes a small change to the `.github/workflows/fossa.yml` file. The change adds a `workflow_dispatch` trigger to the workflow configuration.
* [`.github/workflows/fossa.yml`](diffhunk://#diff-0fb7586e3d92a536569e18dec5c4c7fb63f855d76efdf16ef133c5355013a881R12): Added `workflow_dispatch` trigger to allow manual triggering of the workflow.
> ✨ DAT-18919: Add workflow_dispatch to run manaully

- .github/workflows/sonar.yml
Add new resuable sonar gha workflow
> feat: added recommended sonar gha

- .github/workflows/os-extension-automated-release.yml
This pull request includes a small change to the `.github/workflows/os-extension-automated-release.yml` file. It removes the `permission-security-events: read` line from the workflow configuration.
> DAT-2057 remove permissions scope

- .github/workflows/package.yml
Current script only echoes the string `PR_EXISTS=false`, but does not assign a value to the `PR_EXISTS` variable in the shell environment.
So this line: `echo "PR_EXISTS=false"` just prints a message. It does not do this: `PR_EXISTS=false`. So later when we run `echo "PR_EXISTS=$PR_EXISTS" >> $GITHUB_ENV` the variable `PR_EXISTS` is empty, and GitHub sees it as unset (PR_EXISTS=), which causes the conditional `if: ${{ env.PR_EXISTS == 'false' }}` to fail.
* [`.github/workflows/package.yml`](diffhunk://#diff-170ebc8e4dc40acf23cbe0ecce5f3e2aef1652511f59860db704106b197e1d52L278-R290): Changed the storage of the `PR_EXISTS` variable from `$GITHUB_ENV` to `$GITHUB_OUTPUT` for better alignment with GitHub Actions' recommended practices.
* …
> DAT-20271: update homebrew PR creation

- .github/workflows/package.yml
- src/liquibase-secure/deb/control/control
This pull request updates the packaging workflow and Debian control file to improve deployment and compatibility. The most significant changes involve replacing the dry-run deb signing/upload step with a CloudFront cache invalidation, improving the fallback logic for repository creation tools, and updating the Debian control file to better handle package relationships.
**Workflow and deployment improvements:**
* Removed the dry-run deb signing and upload steps, and replaced them with a CloudFront cache invalidation step that runs only for non-dry-run deployments. This ensures that package updates are immediately visible to users after deployment.
* Enhanced the fallback logic for finding or installing the `createrepo` tool: now prefers `createrepo_c` if available, and installs …
> DAT-20878   DevOps :: APT repo sync issues
