liquibase/build-logic

.github/workflows/lth-docker.yml

liquibase pro license key is required as an env var

bugfix:  add pro license key to env

---

.github/upload_asset.sh
.github/workflows/create-release.yml
.github/workflows/extension-attach-artifact-release.yml
.github/workflows/os-extension-test.yml
.github/workflows/pro-extension-test.yml

https://datical.atlassian.net/browse/DAT-14457
chore(upload_asset.sh): remove unnecessary check for zip files
chore(create-release.yml): update sonar-push.yml version to v0.3.1
chore(extension-attach-artifact-release.yml): update build-logic version to v0.3.1
chore(os-extension-test.yml): update sonar-pull-request.yml version to v0.3.1
chore(pro-extension-test.yml): update sonar-pull-request.yml version to v0.3.1

DAT-14457 Pro Extensions are failing to release due to build-logic bugs

---

.github/workflows/lth-docker.yml

do not require a pro license key

Update lth-docker.yml to not require pro license key

---

.github/package-deb-pom.xml
src/liquibase/deb/control/postinst
src/liquibase/deb/control/postrm

https://datical.atlassian.net/browse/DAT-15708
- refactor(package-deb-pom.xml): update prefix in mapper to /usr/bin for better installation location
- refactor(postinst): update LIQUIBASE_HOME to /usr/bin for better installation location and remove unnecessary code for updating user profiles
- refactor(postrm): unset LIQUIBASE_HOME and remove unnecessary code for updating user profiles

DAT-15708 Incorrect Installation Path for Liquibase APT Package on Github Action Runners

---

.github/workflows/ci-report.yml

Need to test the installation of liquibase-sdk-maven plugin for the failures encountered in ci-report generation :https://github.com/liquibase/build-logic/actions/runs/6276419011

adding workflow_dispatch to test ci-reports

---

.github/workflows/sonar-test-scan.yml

fix: java version 17 for sonar-test-scan
Got a warning from SonarScan and a message from [Slack](https://liquibase.slack.com/archives/C53DX4S4W/p1696351856930289)
Warning: The last analysis has a warning.[See details](https://sonarcloud.io/project/issues)

java version 17 for sonar-test-scan

---

.github/workflows/create-release.yml
.github/workflows/extension-attach-artifact-release.yml
.github/workflows/extension-release-prepare.yml
.github/workflows/extension-release-published.yml
.github/workflows/os-extension-test.yml
.github/workflows/package-deb.yml
.github/workflows/pom-release-published.yml
.github/workflows/pro-extension-test.yml
.github/workflows/sonar-pull-request.yml

https://datical.atlassian.net/browse/DAT-16000
This is to accommodate some oss extensions like the redshift one to execute sonar analysis on PRs with custom build logic

DAT-16000      liquibase-redshift using Liquibase Parent POM

---

.github/release-drafter.yml

feat(release-drafter.yml): add configuration file for release drafter
The release-drafter.yml file is added to the .github directory. This file contains the configuration for the release drafter tool. It specifies the name and tag templates for the releases, as well as the categories for the release notes. The categories include notable changes, new features, bug fixes, breaking changes, API breaking changes, security driver and other updates, and new contributors. The change template is also defined to format the individual changes in the release notes. The version resolver is set up to determine the release type based on labels. Finally, a template is provided to format the full changelog with links to the GitHub repository.

DAT-15655 Release-drafter for extensions

---

.github/workflows/os-extension-test.yml
.github/workflows/pro-extension-test.yml
.github/workflows/sonar-pull-request.yml
.github/workflows/sonar-push.yml

- In os-extension-test.yml and pro-extension-test.yml, change the path for jacoco.xml from **/target/jacoco.exec to **/target/site/jacoco/jacoco.xml. This is done to correctly locate the Jacoco code coverage report.
- In sonar-pull-request.yml and sonar-push.yml, update the name of the test report artifact to test-reports-jdk-17-ubuntu-latest. This is done to ensure consistency in the naming of the test report artifacts across workflows.

chore(workflows): update test report paths in GitHub workflows

---

.github/workflows/create-release.yml
.github/workflows/extension-attach-artifact-release.yml
.github/workflows/extension-release-prepare.yml
.github/workflows/extension-release-published.yml
.github/workflows/os-extension-test.yml
.github/workflows/package-linux.yml
.github/workflows/pom-release-published.yml
.github/workflows/pro-extension-test.yml

chore(create-release.yml): update version of sonar-push.yml to v0.5.8
chore(extension-attach-artifact-release.yml): update version of get_draft_release.sh, sign_artifact.sh, and upload_asset.sh to v0.5.8
chore(extension-release-prepare.yml): update version of extension-release-rollback.yml to v0.5.8
chore(extension-release-published.yml): update version of extension-release-prepare.yml to v0.5.8
chore(os-extension-test.yml): update version of sonar-pull-request.yml to v0.5.8
chore(package-linux.yml): update version of package-deb-pom.xml and sign_artifact.sh to v0.5.8
chore(pom-release-published.yml): update version of extension-release-prepare.yml to v0.5.8
chore(pro-extension-test.yml): update version of sonar-pull-request.yml to v0.5.8

DAT-16417 Extensions nightly build review

---

.github/workflows/extension-release-published.yml

chore(extension-release-published.yml): remove duplicate maven-release job and add maven-release job to run after release job with extraCommand input

DAT-16372 DevOps :: Incoherent extension release

---

.github/workflows/extension-release-prepare.yml
.github/workflows/extension-release-rollback.yml
.github/workflows/os-extension-automated-release.yml
.github/workflows/os-extension-test.yml
.github/workflows/pro-extension-test.yml
.github/workflows/sonar-pull-request.yml
.github/workflows/sonar-test-scan.yml

chore(workflows): update actions/upload-artifact and actions/download-artifact versions to v3
The actions/upload-artifact and actions/download-artifact versions have been updated from v4 to v3 in the following workflow files:
- .github/workflows/extension-release-prepare.yml
- .github/workflows/extension-release-rollback.yml
- .github/workflows/os-extension-automated-release.yml
- .github/workflows/os-extension-test.yml
- .github/workflows/pro-extension-test.yml
- .github/workflows/sonar-pull-request.yml
- .github/workflows/sonar-test-scan.yml
This update was done to ensure compatibility with the latest versions of the actions and to take advantage of any bug fixes or improvements introduced in the new versions.

DAT-16593 Downgrade upload/download artifacts for extensions

---

.github/workflows/package-linux.yml

fix(package-linux.yml): update AWS credentials configuration to use GitHub OIDC role for improved security
feat(package-linux.yml): add permissions for id-token and contents to allow write access and read access respectively

DAT-11513      DevOps :: Enable OIDC for Github / AWS Integration

---

.github/workflows/create-release.yml
.github/workflows/extension-attach-artifact-release.yml
.github/workflows/extension-release-prepare.yml
.github/workflows/extension-release-published.yml
.github/workflows/os-extension-test.yml
.github/workflows/package.yml
.github/workflows/pom-release-published.yml
.github/workflows/pro-extension-test.yml
README.md

I added the logic shown at https://sdkman.io/vendors
The send command has an `URL` input parameter where the package must be accessible, ~~that is why I created an **Artifactory** public repo `https://artifactory.datical.net/artifactory/sdkman` to store them~~ so its is uploaded to our package repo `s3://repo.liquibase.com/sdkman`. We will have download insights as well. An example of a POST request to send a new version to SDKMAN:
```
curl -X POST \
-H "Consumer-Key: ******" \
-H "Consumer-Token: *******" \
-H "Content-Type: application/json" \
-H "Accept: application/json" \
-d '{"candidate": "liquibase", "version": "4.26.0", "url": "https://s3.amazonaws.com/repo.liquibase.com/sdkman/liquibase-4.26.0.zip"}' \
https://vendors.sdkman.io/release
```
Vendor logic tested from …

DAT-16972 SDKMAN Distribution

---

.github/workflows/package.yml

Tested here: https://github.com/liquibase/liquibase-packaging/actions/runs/8468556298/job/23201864058
Automatic PR created by liquibot for `4.27.0`: https://github.com/Homebrew/homebrew-core/pull/167383

fix for homebrew update process

---

.github/workflows/codeql.yml

fix:`.github/workflows/codeql.yml`: [codeql fails in hashicorp with 401 Unauth ](https://github.com/liquibase/hashicorp-vault-plugin/actions/runs/8913021766/job/24477876453#step:7:75).
Successful run when built with adding: maven-settings-xml-action: https://github.com/liquibase/hashicorp-vault-plugin/actions/runs/8913988741
comments on the ticket: https://datical.atlassian.net/browse/DAT-17435?focusedCommentId=141375

Codeql issue hashicorp

---

.github/workflows/slack-notification.yml

fix: `.github/workflows/slack-notification.yml`: if the `event.action` equals `'test-failure'`, `SLACK_COLOR` will be set to `'danger'` resulting red in Slack bar, indicating a failure.

change slack color to red incase of failure

---

.github/workflows/os-extension-test.yml

The tests are now running against the PR code and not main branch.
Before that, the tests of the main branch were run, but not the PR tests... that caused e.g. that the automerge of https://github.com/liquibase/liquibase-percona/pull/457 failed the build.

os-extension-test: fix checkout ref

---

.github/workflows/pro-extension-test.yml

Respect new argument when uploading artifacts. Use extra maven args when making the initial package.
There is a place that may need to be updated when _downloading_ the artifacts but currently I'm not sure if that's necessary. I only intend on letting you point to say `scripting/target/*`. Let me know what you think!

DAT-18178: Add artifact path optional parameter to extension test workflow.

---

.github/workflows/build-publish-liquibase-checks.yml

Currently only deploys to GPM. This change updates to upload to the workflow as well for easier testing.

DAT-18178: Upload multiplatform artifacts for checks extension workflow

---

.github/workflows/build-publish-liquibase-checks.yml

Keeps most of the same behavior but hardcodes less things. `inputs.version` was required, but there were a lot of places that had `if: !inputs.version`, so i removed these. 
Here's an outline of what this does:
1. Check out liquibase oss and pro on appropriate branches (now workflow inputs).
2. Build liquibase oss and core to get the necessary dependencies to build `liquibase-checks`. We are building this without setting any versions, so this will be installed under version `0-SNAPSHOT` in this workflow. The true version will correspond to the input branches.
3. Build liquibase-checks for each platform
4. Upload each of the platforms liquibase-checks jars to the workflow. << ✨ new
5. After this workflow has completed for windows, linux and macos we kick off a new workflow to combine …

DAT-18153: Make multiplatform checks extension workflow work with PRs

---

.github/workflows/package.yml

fix: `.github/workflows/package.yml`: remove -d option as it is directing to an extra folder. 
Error: https://github.com/liquibase/liquibase/actions/runs/10096594193/job/27919506000#step:16:173

remove -d to folder

---

.github/workflows/extension-release-published.yml

feat: `.github/workflows/extension-release-published.yml`: add a `deployToMavenCentral` input parameter
NOTE : if you don't push to sonatype, you don't release to maven

🔧 DAT-18295: add a toggle to deployToMavenCentral

---

.github/workflows/os-extension-automated-release.yml

https://datical.atlassian.net/browse/DAT-18307
🔧 (os-extension-automated-release.yml): improve retrieval of draft release ID by sorting releases by created_at date and selecting the last one to ensure the newest draft release ID is used

DAT-18307  DevOps :: Extension release fails when 2 drafts have the same name

---

.github/release-drafter.yml
.github/workflows/create-release.yml
.github/workflows/extension-attach-artifact-release.yml
.github/workflows/extension-release-prepare.yml
.github/workflows/extension-release-published.yml

https://datical.atlassian.net/browse/DAT-18309

DAT-18309 DevOps :: Extensions are creating 2 tags

---

.github/workflows/package.yml

🔧 (package.yml): add installation step for GitHub CLI to enable usage in the workflow
🔧 (package.yml): introduce a step to check for an existing Homebrew formula PR before updating it to avoid creating duplicate PRs

DAT-18283 DevOps :: Homebrew failure

---

.github/workflows/extension-attach-artifact-release.yml

use bash in windows runners to avoid syntax mismatches
https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idstepsshell

use bash shell in windows runners due to required syntax

---

.github/workflows/pro-extension-test.yml

I don't actually know if this is going to work, but this currently fails on Windows builds:
https://github.com/liquibase/liquibase-checks/actions/runs/10374118321/job/28720832834?pr=72#step:11:15

use bash shell for artifact ID and version

---

.github/workflows/pro-extension-test.yml

Using the new "proper" way seems to have broken the build. Switching back to the old build, and @sayaliM0412 will look into fixing this properly.

use old method for exporting variables

---

.github/workflows/create-release.yml

🔧 (create-release.yml): add support for running Sonar scan by introducing a new 'sonar' input parameter with a default value of true

DAT-18326 test-harness is failing at createRelease step

---

.github/workflows/os-extension-automated-release.yml

📝 (os-extension-automated-release.yml): add 'liquibase-parent-pom' repository to the default list of repositories to release in the workflow configuration

DAT-18286  DevOps :: Bump liquibase-parent-pom liquibase.version

---

.github/workflows/pro-extension-test.yml

- specify shell: bash, it will run the commands in a Bash shell, capable of executing Linux commands.
- extra step for Running Windows Command

🔧 use shell:bash to run Linux commands

---

.github/workflows/pro-extension-test.yml

fix: `.github/workflows/pro-extension-test.yml` : use version 3 of `actions/download-artifact`. 
failing workflows : https://github.com/liquibase/liquibase-checks/actions/runs/10796187033/job/29945308542?pr=90
`Error: This request has been automatically failed because it uses a deprecated version of ``actions/download-artifact: v2``. Learn more: https://github.blog/changelog/2024-02-13-deprecation-notice-v1-and-v2-of-the-artifact-actions/`

🔧 Update actions/download-artifact version

---

.github/workflows/pom-release-published.yml

This PR reflect changes made on parent-pom project, as a pom project do not requires source and javadoc.

chore: do not release sources and javadoc for pom project

---

.github/workflows/pro-extension-test.yml

The path to the `fileslist.txt` files that are needed to combine the `liquibase-checks` platform JARs has changed.

Change path for combineJars for GraalPy 24.1.1

---

.github/workflows/extension-attach-artifact-release.yml

When building multi-platform artifacts we upload an `Event File` object to the workflow. This will work once then fail on subsequent platform builds because the file already exists. I chose to remove this step because this file is not used anywhere.

Remove unnecessary upload of event.json

---

.github/workflows/os-extension-test.yml

This pull request includes a change to the `.github/workflows/os-extension-test.yml` file to update the version of the `sonar-pull-request.yml` workflow being used.
* [`.github/workflows/os-extension-test.yml`](diffhunk://#diff-43ea773ed34788e59031ecce17de6fe3c738530fa5aaaab22805ebf12ab58001L258-R258): Updated the `uses` line to reference the `main` branch of the `liquibase/build-logic/.github/workflows/sonar-pull-request.yml` instead of a specific version (`v0.7.8`).

🔧 Need to keep upload and download artifact on same version

---

.github/workflows/pro-extension-test.yml
.github/workflows/sonar-pull-request.yml
.github/workflows/sonar-push.yml

This pull request includes changes to the GitHub Actions workflows to update the AWS authentication method from using access keys to using OIDC roles.
Changes to GitHub Actions workflows:
* [`.github/workflows/pro-extension-test.yml`](diffhunk://#diff-ae1893afdebf217a3d21c6073d1a9d3b3ea3792ecd74048de56ff0dba952ec8cL68-R74): Replaced `GHA_AWS_KEY_ID` and `GHA_AWS_KEY` with `AWS_GITHUB_OIDC_ROLE_ARN_S3_GHA` for AWS authentication.
* [`.github/workflows/sonar-pull-request.yml`](diffhunk://#diff-fc000050ca00a39fcce28bc1e5b62492255b4c9cb8b333da82c2202975892a43L28-R28): Updated the environment variables to use `AWS_GITHUB_OIDC_ROLE_ARN_S3_GHA` instead of `GHA_AWS_KEY_ID` and `GHA_AWS_KEY`.
* [`.github/workflows/sonar-push.yml`](diffhunk://#diff-3cf0243751c2d2f0a56ede5613cabea668e70c7469a6c737414 …

CRUC-58 DevOps :: Remove Individual IAM Users and Transition to OIDC or Specific Static Credentials

---

.github/workflows/extension-deploy-master-snapshot.yml

This pull request introduces a new GitHub Actions workflow for deploying master snapshots. The workflow is triggered by pushes to the `main` branch and includes steps for setting up the Java Development Kit (JDK), configuring Maven settings, updating the project version, and deploying the snapshot.
Key changes:
* [`.github/workflows/extension-deploy-master-snapshot.yml`](diffhunk://#diff-1b971d3626975dfeabd0ea768d67c2df4af2174804ded98b4f7f1377e75ca483R1-R75): Added a new workflow named `Deploy Master Snapshot` that runs on `ubuntu-latest` and includes steps for checking out code, setting up JDK 17, configuring Maven settings, updating the project version to `master-SNAPSHOT`, and building and deploying the snapshot.

DAT-19350 configure test-harness to deploy master-snapshot to GPM

---

.github/workflows/os-extension-automated-release.yml

This pull request includes a change to the `.github/workflows/os-extension-automated-release.yml` file. The change updates the default list of repositories to release by removing the `liquibase-parent-pom` repository from the list.
* [`.github/workflows/os-extension-automated-release.yml`](diffhunk://#diff-968011793292fda6afa390798b1dc766d4d0a935081ccc4949a4458c7952e206L13-R13): Removed `liquibase-parent-pom` from the default list of repositories to release.

DAT-18940 Automated extensions release is errorenously changing the version of the parent-pom

---

.github/workflows/create-release.yml

This pull request includes a small change to the `.github/workflows/create-release.yml` file. The change adds permissions to write checks for the workflow. Based on the issue discussed here: https://github.com/dorny/test-reporter/issues/229
* [`.github/workflows/create-release.yml`](diffhunk://#diff-8ac33fe295df086d3e55df1eb01194819d34cc0f5f54076dba96ceac0e40bd79R21-R22): Added `permissions` with `checks: write` to the workflow configuration.

🔧 DAT-19449: update permissions

---

.github/workflows/create-release.yml

This pull request includes a small change to the `.github/workflows/create-release.yml` file. The change removes the `permissions` section, specifically the `checks: write` permission, from the workflow configuration.
* [`.github/workflows/create-release.yml`](diffhunk://#diff-8ac33fe295df086d3e55df1eb01194819d34cc0f5f54076dba96ceac0e40bd79L21-L22): Removed the `permissions` section, including the `checks: write` permission.

Delete checks permissions

---

.github/workflows/extension-attach-artifact-release.yml

This pull request includes a change to the GitHub Actions workflow configuration file `.github/workflows/extension-attach-artifact-release.yml`. The change introduces a concurrency group to the build and package job to prevent multiple runs from interfering with each other.
* [`.github/workflows/extension-attach-artifact-release.yml`](diffhunk://#diff-dfefa73bb010891f1244099cfb9fadddfb8445cde54e8cdd4c9eea9f24e255d9R71-R72): Added a `concurrency` group to the build and package job to ensure that only one job runs at a time for the same reference.

🔧 use concurrency group to run one job at a time during PR merges

---

.github/workflows/build-extension-jar.yml

It has a default but it's required

Remove not required required

---

.github/workflows/generate-upload-fossa-report.yml

This pull request includes changes to the `.github/workflows/generate-upload-fossa-report.yml` file to enhance the handling of version numbers during the FOSSA report generation and upload process.
Changes in environment variables:
* Added `VERSION_NUMBER` environment variable to utilize the input version number for report generation.
Changes in S3 upload command:
* Modified the S3 upload command to use the newly defined `VERSION_NUMBER` environment variable instead of the previous direct reference to `github.event.inputs.version_number_for_report_generation`.

🔧 : Ensure VERSION_NUMBER is populated correctly when the workflow is triggered by workflow_call.

---

.github/workflows/fossa.yml
.github/workflows/generate-upload-fossa-report.yml

This pull request includes updates to the GitHub Actions workflows to use the latest version of the `upload-artifact` action.
* [`.github/workflows/fossa.yml`](diffhunk://#diff-0fb7586e3d92a536569e18dec5c4c7fb63f855d76efdf16ef133c5355013a881L151-R151): Updated the `upload-artifact` action from version 3 to version 4.
* [`.github/workflows/generate-upload-fossa-report.yml`](diffhunk://#diff-80879043f56f0d1ad5339d692506295927c2dc42208a159d095c4a2a45c87b41L76-R76): Updated the `upload-artifact` action from version 3 to version 4.

update actions/upload-artifact version to v4

---

.github/package-deb-pom.xml
src/liquibase/deb/control/postinst

This pull request includes changes to update the installation directory of Liquibase within the Debian package configuration. The most important changes include modifying the directory prefix in the `.github/package-deb-pom.xml` file and updating the `LIQUIBASE_HOME` environment variable in the `postinst` script.
Changes to installation directory:
* [`.github/package-deb-pom.xml`](diffhunk://#diff-7ba03948b348b869252b6a868a4da5fed7cfed73a962c52b029578b170a6517dL59-R59): Changed the directory prefix from `/usr/bin` to `/opt/liquibase` to align with the new installation path.
* [`src/liquibase/deb/control/postinst`](diffhunk://#diff-3477e4c9d7cea3a345126174f85c9f7b993f82909c831d1e089925f1dbf33f85L4-R4): Updated the `LIQUIBASE_HOME` environment variable to reflect the new installation …

[GHSA-pj29-2cg8-7jjm] Refusal to Install Liquibase on Production and Pre-production Servers Due to Packaging and Security Concerns

---

.github/workflows/fossa_ai.yml

This pull request includes a small change to the `.github/workflows/fossa_ai.yml` file. The change ensures that the code checkout step in the workflow fetches the entire history by setting the `fetch-depth` to 0 and checks out the specific branch or tag referenced by `github.ref`.

🔧 checkout ref value

---

.github/workflows/ephemeral-cloud-infra.yml

This pull request includes updates to the `.github/workflows/ephemeral-cloud-infra.yml` file to add support for deploying or destroying AWS Redshift infrastructure.
Changes to support AWS Redshift:
* Added `aws_redshift` as an input parameter with a description, required status, type, and default value.
* Updated the `jobs` section to set the environment variable `TF_VAR_create_aws_redshift` based on the new `aws_redshift` input parameter.

DAT-19298 DevOps :: Refactor test.yml to use localstack for redshift extensions

---

.github/workflows/package.yml

This pull request includes a small change to the `.github/workflows/package.yml` file. The change ensures that the `PR_EXISTS` environment variable is correctly checked as a string in the conditional statement.
* [`.github/workflows/package.yml`](diffhunk://#diff-170ebc8e4dc40acf23cbe0ecce5f3e2aef1652511f59860db704106b197e1d52R244-R248): Modified the conditional check for `PR_EXISTS` to compare it as a string ('false') instead of a boolean (false).

🔧 homebrew PR creation issue

---

.github/workflows/fossa_ai.yml

This pull request includes changes to the `.github/workflows/fossa_ai.yml` file to enhance the workflow for generating and uploading FOSSA SBOM reports. The most important changes include adding new input parameters, modifying conditions for job execution, and updating steps to use these new inputs.
Enhancements to workflow inputs and conditions:
* Added `description` for the `repo_name` input and introduced a new `branch_name` input to the workflow.
* Modified the condition for the `fossa-scan` job to run only on specific events (`repository_dispatch` and `workflow_dispatch`).
* Changed the condition for the `generate-oss-pro-sbom-reports` job to simplify the event checks.
Updates to job steps:
* Added a `Setup` step to extract and set up necessary inputs like `repo_name`, …

🔧 : Fix/generate-oss-pro-sbom-reports

---

.github/workflows/pro-extension-test.yml

This pull request includes a conditional update to the `sonar-pr` job within the `.github/workflows/pro-extension-test.yml` file. The change ensures that the job only runs when the `nightly` input is false and the `java` input is set to '17' as the [sonar-pull-request.yml](https://github.com/liquibase/build-logic/blob/main/.github/workflows/sonar-pull-request.yml#L104) expects `test-reports-jdk-17-ubuntu-latest` artifacts
* [`.github/workflows/pro-extension-test.yml`](diffhunk://#diff-ae1893afdebf217a3d21c6073d1a9d3b3ea3792ecd74048de56ff0dba952ec8cL448-R448): Updated the condition for the `sonar-pr` job to check both `inputs.nightly` and `inputs.java` values.

🔧 Update sonar-pr condition to include Java 17 check

---

.github/workflows/fossa_ai.yml

This pull request includes a change to the `.github/workflows/fossa_ai.yml` file to update the S3 bucket paths for uploading OSS FOSSA results. The most important change is the modification of the S3 bucket name to a new destination.
Changes to S3 bucket paths:
* [`.github/workflows/fossa_ai.yml`](diffhunk://#diff-16fa3dae8fcf42e25227fd7efbf7683e56bb393265c17267bd5a6eada811edfeL223-R225): Updated the S3 bucket paths from `s3://liquibaseorg-origin/sbom-lb-lbpro-releases/` to `s3://liquibase-release-sboms/sbom-lb-lbpro-releases/` for uploading OSS FOSSA results.

🔧 update s3 location for sboms

---

.github/workflows/extension-release-published.yml

This pull request updates the GitHub Actions workflow configuration to use a newer version of the Ubuntu runner.
* [`.github/workflows/extension-release-published.yml`](diffhunk://#diff-8f35892fff793298c429a326782b9912e79873322b834b9f18da1b918718e39aL288-R288): Changed the `runs-on` parameter for the `deploy_xsd` job from `ubuntu-20.04` to `ubuntu-22.04`.

🔧 Update workflow to use Ubuntu 22.04 for deployment

---

.github/workflows/pro-extension-test.yml

NOTE: not all pro-extensions need the Azure-secrets. Hence, adding `required: false` for the Azure secrets.

🔧 Update pro-extension-test.yml secrets requirements

---

.github/workflows/publish-for-liquibase.yml

The multimodule pom project in liquibase-checks was refactored into a single project, and thus, the artifact is not in a subdirectory.

DAT-19650: remove artifact path because liquibase-checks was refactored

---

.github/workflows/pro-extension-test.yml

- To facilitate the publication of artifacts to GPM here in azure-extension for checks to consume it : I need to upload `${{ steps.get-artifact-id.outputs.artifact_id }}-artifacts` to the build page here: https://github.com/liquibase/liquibase-azure-extension/actions/runs/13721607940. 
- Resolving issue of `The following artifacts could not be resolved: org.liquibase.ext:liquibase-azure-extension:jar:1.0.0-SNAPSHOT (absent)` https://github.com/liquibase/liquibase-checks/actions/runs/13638267536/job/38144289006#step:13:2521

✨ DAT-19740: upload ${{ steps.get-artifact-id.outputs.artifact_id }}-artifacts

---

.github/workflows/extension-attach-artifact-release.yml

Why the change ?
-> https://datical.atlassian.net/browse/DAT-19850?focusedCommentId=161891
There are 2 issues here: 
Issue1: Race Condition Between Concurrent PRs ticket [DAT-18547](https://datical.atlassian.net/browse/DAT-18547) - resolved, solution was to  use the concurrency feature to cancel in-flight jobs and only keep the latest for a specific ref hence using ${{ github.ref }} 
Issue2: Current issue, the real problem lies in how thhe above concurrency is applied per OS runner. As we are doing a matrix build across our OS’s -ubuntu-latest, macos-latest, windows-latest, the same concurrency.group is shared by all of them. That means:
When one OS’s job is running eg: windowsOS -> a job on another OS eg: MacOS for the same ref is getting canceled even though it's part of the same …

🔧 DAT-19850: edit concurrency group based on os

---

.github/workflows/package.yml

hotfix for SDKman to reference the Cloudfront Distribution, not the S3 bucket directly

hotfix for SDKman to reference the Cloudfront Distribution

---

.github/workflows/package.yml

This pull request makes a small change to the `.github/workflows/package.yml` file by removing a step that ensured public access was enabled for specific S3 buckets. 
* Removed the step that used `aws s3api put-bucket-acl` commands to grant public read access to the `repo.liquibase.com` and `repo.liquibase.com.dry.run` S3 buckets.

Fix: Remove public ACL for s3 repo.liquibase.com

---

.github/workflows/build-extension-jar.yml
.github/workflows/codeql.yml
.github/workflows/create-release.yml
.github/workflows/dependabot-automerge.yml
.github/workflows/ephemeral-cloud-infra.yml
.github/workflows/extension-attach-artifact-release.yml
.github/workflows/extension-release-prepare.yml
.github/workflows/extension-release-published.yml
.github/workflows/extension-release-rollback.yml
.github/workflows/fossa.yml
.github/workflows/fossa_ai.yml
.github/workflows/os-extension-automated-release.yml
.github/workflows/os-extension-test.yml
.github/workflows/owasp-scanner.yml
.github/workflows/package.yml
.github/workflows/pom-release-published.yml
.github/workflows/pro-extension-build-for-liquibase.yml
.github/workflows/pro-extension-test.yml
.github/workflows/publish-for-liquibase.yml
.github/workflows/slack-notification.yml
.github/workflows/sonar-jest-coverage.yml
.github/workflows/sonar-pull-request.yml
.github/workflows/sonar-push.yml
.github/workflows/sonar-test-scan.yml
README.md

This pull request updates GitHub Actions workflows to improve security by removing hardcoded credentials and refines the release process by adding new files to the artifact path. The most important changes include removing the use of `secrets.BOT_TOKEN` and adding `release.properties` to the release files.
* [`.github/workflows/extension-release-prepare.yml`](diffhunk://#diff-44f871857d0892b2cdf6de28995341916f0cbe2bcc66f0412df9399c6d0f81f3L25-L26): Removed the `GITHUB_TOKEN` environment variable and references to `${{ secrets.BOT_TOKEN }}` in Maven commands to improve security. [[1]](diffhunk://#diff-44f871857d0892b2cdf6de28995341916f0cbe2bcc66f0412df9399c6d0f81f3L25-L26) [[2]](diffhunk://#diff-44f871857d0892b2cdf6de28995341916f0cbe2bcc66f0412df9399c6d0f81f3L101-R99)
* …

DAT-20127 refactor: remove sensitive credentials from Maven commands in workflows

---

.github/workflows/pro-extension-test.yml

This pull request updates the `.github/workflows/pro-extension-test.yml` file to integrate HashiCorp Vault for managing secrets. The changes introduce new inputs, environment variables, and job steps to support Vault-based authentication and token setup.
* Added new inputs `vaultAddr` and `vaultNamespace` to specify the Vault server address and namespace, respectively. These inputs are optional and have default empty values.
* Introduced two new secrets, `VAULT_ROLE_ID` and `VAULT_SECRET_ID`, for AppRole-based authentication with Vault.
* Set new environment variables `LIQUIBASE_VAULT_ADDR` and `LIQUIBASE_VAULT_NAMESPACE` based on the provided inputs.
* Added a job step to set up a Vault token using the `hashicorp/vault-action@v3` GitHub Action. This step is conditional on the presence of …

DAT-19745: add support for obtaining Hashicorp Vault tokens to pro-extension-test.yml

---

.github/workflows/package.yml

This pull request updates the `.github/workflows/package.yml` file to enhance the configuration of the `deb-s3 upload` command by adding a new `--visibility=nil` option. This change ensures that the visibility of uploaded packages is explicitly set to `nil`, which may address specific requirements for package visibility during the upload process.
* Added the `--visibility=nil` option to the `deb-s3 upload` command in the main package upload step to explicitly set the visibility of uploaded `.deb` packages. (`.github/workflows/package.yml`, [.github/workflows/package.ymlL176-R176](diffhunk://#diff-170ebc8e4dc40acf23cbe0ecce5f3e2aef1652511f59860db704106b197e1d52L176-R176))
* Added the `--visibility=nil` option to the `deb-s3 upload` command in the dry-run package upload step to ensure …

🔧 (package.yml): update deb-s3 upload commands to include visibility option for improved package management

---

.github/workflows/package.yml

This pull request makes a minor update to the GitHub Actions workflow configuration by removing unused permissions from the `upload_packages` job.
Workflow configuration changes:
* [`.github/workflows/package.yml`](diffhunk://#diff-170ebc8e4dc40acf23cbe0ecce5f3e2aef1652511f59860db704106b197e1d52L86-L88): Removed the `id-token: write` and `contents: read` permissions from the `upload_packages` job, as they are no longer needed.

DAT-20252 : use permission-pull-requests: write for Github App Permissions 

---

.github/workflows/os-extension-automated-release.yml

This pull request updates the `.github/workflows/os-extension-automated-release.yml` file to replace the use of the default GitHub token with a GitHub App token for enhanced security and permissions management. The changes ensure that API calls in the workflow use the GitHub App token instead of the default `GITHUB_TOKEN`.
* Added a new step to generate a GitHub App token (`actions/create-github-app-token@v2`) with the required permissions (`permission-security-events`, `permission-contents`, and `permission-releases`) for interacting with repositories. [[1]](diffhunk://#diff-968011793292fda6afa390798b1dc766d4d0a935081ccc4949a4458c7952e206R36-R51) [[2]](diffhunk://#diff-968011793292fda6afa390798b1dc766d4d0a935081ccc4949a4458c7952e206R179-R195)
* Updated all API calls in the workflow to …

🔧 DAT-20257: fix os-extension-automated-release with Github App token

---

.github/workflows/os-extension-automated-release.yml

This pull request updates the `.github/workflows/os-extension-automated-release.yml` file to improve security by replacing the use of the default `GITHUB_TOKEN` with a GitHub App token. This ensures more granular permissions and better control over repository access. The most important changes include adding a step to generate the GitHub App token, updating token references in various steps, and removing unnecessary environment variables.
* Added a new step to generate a GitHub App token using the `actions/create-github-app-token@v2` action. This token is configured with the necessary permissions and replaces the default `GITHUB_TOKEN`. (`[.github/workflows/os-extension-automated-release.ymlR92-R105](diffhunk://#diff-968011793292fda6afa390798b1dc766d4d0a935081ccc4949a4458c7952e206R92-R105) …

DAT-20257 fix permissions for updating POMs

---

.github/workflows/os-extension-automated-release.yml

This pull request updates the `.github/workflows/os-extension-automated-release.yml` file to integrate GitHub App authentication into the workflow. The changes ensure secure access to repositories using a GitHub App token and enable Dependabot to run with the appropriate permissions.
* Added a step to generate a GitHub App token using the `actions/create-github-app-token@v2` action. This step retrieves the token based on the app ID, private key, repository owner, and target repository. (`[.github/workflows/os-extension-automated-release.ymlR71-R79](diffhunk://#diff-968011793292fda6afa390798b1dc766d4d0a935081ccc4949a4458c7952e206R71-R79)`)
* Updated the Dependabot step to use the GitHub App token by setting the `GH_TOKEN` environment variable with the token generated in the previous step. …

DAT-20257 🔧 (os-extension-automated-release.yml): add GitHub App token retrieval for Dependabot updates

---

.github/workflows/cleanup-individual-artifacts.yml
.github/workflows/extension-attach-artifact-release.yml
.github/workflows/pro-extension-build-for-liquibase.yml
.github/workflows/pro-extension-test.yml
README.md

This pull request introduces a new reusable GitHub Actions workflow for cleaning up individual OS-specific artifacts and integrates it into multiple existing workflows. The changes aim to streamline artifact cleanup and reduce unnecessary storage usage.
* [`.github/workflows/cleanup-individual-artifacts.yml`](diffhunk://#diff-c1c297045036892cf6d46e2f4678bef3a456994067f6402fecea8e6353f9de8fR1-R36): Added a new reusable workflow named "Cleanup Individual OS Artifacts" that deletes OS-specific artifacts (`ubuntu-latest`, `macos-latest`, and `windows-latest`) using the `geekyeggo/delete-artifact@v5` action. It accepts `artifact_id` and `artifact_version` as inputs.
* [`.github/workflows/extension-attach-artifact-release.yml`](diffhunk://#diff-dfefa73bb010891f1244099cfb9fadddfb8445cde54e8cdd4c9 …

DAT-20250 DevOps: delete individual checks artifacts after multiplatform artifact is created

---

.github/workflows/extension-attach-artifact-release.yml
.github/workflows/os-extension-test.yml

This pull request updates the `.github/workflows/os-extension-test.yml` file to enhance configurability and streamline the CI workflow. Key changes include the addition of new input parameters, dynamic JDK version setup, and conditional execution of SonarQube analysis.
* Added a new input parameter `javaBuildVersion` to allow specifying the Java version dynamically, with a default value of `17`.
* Introduced a `skipSonar` input parameter to enable skipping SonarQube analysis, with a default value of `false`.
* Updated the JDK setup step to use the `javaBuildVersion` input dynamically instead of hardcoding Java version `17`.
* Modified the `sonar-pr` job condition to respect the new `skipSonar` input, ensuring SonarQube analysis can be skipped when desired.
Working example: …

feat: add configurable Java build version to os-extension-test.yml

---

.github/workflows/create-release.yml
.github/workflows/pro-extension-test.yml

Searching our entire repo, only commercial-databricks is using `artifactPath` parameter: https://github.com/search?q=org%3Aliquibase+artifactPath%3A+NOT+repo%3Aliquibase%2Fbuild-logic&type=code . 
And sonar is failing for it, as it should not consider the path in this case. This removes this parameter.
Test run: https://github.com/liquibase/liquibase-commercial-databricks/actions/runs/15568496305/job/43838740890?pr=93

ArtifactPath should not be used by Sonar

---

.github/workflows/extension-attach-artifact-release.yml

This pull request makes minor adjustments to the `.github/workflows/extension-attach-artifact-release.yml` file by removing the `working-directory` property from two job steps. These changes ensures that the job build everything in the default working directory before starting to collect the artifacts.
Working example: https://github.com/liquibase/liquibase-commercial-databricks/actions/runs/15591182850

Fix usage of artifact path

---

.github/workflows/extension-release-published.yml

`working-directory` parameter is used only by commercial versions of databricks and mongodb . That's the first time we used them and we faced some release issues, that were fixed in this branch. 
Successful execution is here: https://github.com/liquibase/liquibase-commercial-databricks/actions/runs/16326434130

fix-databricks-release

---

.github/workflows/os-extension-test.yml

so far, only unit tests are run. while it'd be great to just run integration tests for all open source extensions this is a breaking change in case some extension did not configure the failsafe plugin correctly (unlikely) or has failing integration tests. thus this is introduced as a new optional feature. if/when most/all plugins have explicitly enabled this the default should be switched to `true`. the template plugin repo should be updated to enable this so that new plugins start with running integration tests.
maven integration tests generate reports in the same format as unit tests which are however stored in `failsafe-reports`. thus these also need to be picked up for further processing by Sonar.
this also resolves that the build so far failed if _no_ unit test was present (the …

`os-extension-test`: add option to run integration tests

---

.github/actions/setup-google-credentails/action.yml

This pull request introduces a new GitHub Action to set up Google credentials for authentication. The action retrieves credentials from AWS Secrets Manager and configures them for use in workflows.
* **Action Definition**: Added a new composite action in `.github/actions/setup-google-credentails/action.yml` named `Setup Google Credentials`. This action retrieves Google credentials from AWS Secrets Manager and configures authentication for workflows.
* **Inputs**:
- [`aws-region`](diffhunk://#diff-40c2702a270ac9333e598b682c09d06d31439868953da5007477ff88c68c97d1R1-R28): Optional input with a default value of `us-east-1` to specify the AWS region for vault access.
- [`vault-secret-id`](diffhunk://#diff-40c2702a270ac9333e598b682c09d06d31439868953da5007477ff88c68c97d1R1-R28): Optional input …

DAT-20504: feat: add setup action for Google credentials retrieval and authentication

---

.github/workflows/subtree-sync.yml

This is desirable because even with conflicts, we still want to use merge commits, not squash or rebase merges. The developers use squash merges by default, so it is easy for us to accidentally squash merge them, which does not properly resolve the conflict.

subtree-sync: mark PR as auto-merge even if conflicts are detected

---

.github/workflows/build-extension-jar.yml
.github/workflows/extension-attach-artifact-release.yml
.github/workflows/package.yml
CLAUDE.md

This PR addresses a **CRITICAL security vulnerability** where GPG private keys and passphrases are exposed in GitHub Actions logs.
With the switch from GitHub Actions secrets to AWS Secrets Manager (PR #359), the private GPG signing key is no longer properly masked in build logs. The key is visible in logs when passed to the `crazy-max/ghaction-import-gpg@v6` action.
Additionally, the `package.yml` workflow contained insecure command-line passphrase usage that would expose the GPG passphrase in logs.
- Added proper masking using the `::add-mask::` command with URL encoding before the GPG key is used
- Fixed timing vulnerability identified by Copilot: keys are now masked IMMEDIATELY after capture, before any potential log exposure
- Applied consistent security pattern across all affected …

CRITICAL SECURITY FIX: Mask GPG private key in GitHub Actions logs

---

.github/package-deb-pom-secure.xml
.github/workflows/package.yml
src/liquibase-secure/deb/control/control
src/liquibase-secure/deb/control/postinst
src/liquibase-secure/deb/control/postrm

This pull request updates the `.github/workflows/package.yml` workflow to support publishing both the community (`liquibase`) and secure (`liquibase-secure`) Homebrew formulas, with improved flexibility for artifact download sources. The changes make the workflow configurable for the formula name and download URL, allowing it to handle different release and packaging requirements for each formula.
**Homebrew formula support and configuration:**
* Added new workflow inputs: `formula_name` (to specify which Homebrew formula to update) and `download_base_url` (to specify the base URL for downloading release artifacts). Defaults are set for both inputs. [[1]](diffhunk://#diff-170ebc8e4dc40acf23cbe0ecce5f3e2aef1652511f59860db704106b197e1d52R33-R42) …

DAT-20673 Secure: Create new package locations

---

.github/workflows/codeql.yml

this is required to support projects which use a different JDK version (e.g. 21).
the default stays at 17 and thus does not change for any existing consumers.

make java version configurable for CodeQL

---

.github/workflows/codeql.yml
.github/workflows/extension-attach-artifact-release.yml
.github/workflows/extension-release-prepare.yml
.github/workflows/extension-release-published.yml
.github/workflows/extension-release-rollback.yml
.github/workflows/lth-docker.yml
.github/workflows/os-extension-test.yml
.github/workflows/owasp-scanner.yml
.github/workflows/package.yml
.github/workflows/pom-release-published.yml
.github/workflows/pro-extension-build-for-liquibase.yml
.github/workflows/pro-extension-test.yml
.github/workflows/publish-for-liquibase.yml
.github/workflows/sonar-pull-request.yml
.github/workflows/sonar-push.yml
.github/workflows/sonar-test-scan.yml

This pull request removes support for Java 8 and 11, and updates the GitHub workflows to use Java 21. These changes align the project with newer versions of Java, ensuring compatibility and leveraging modern features.

Remove Java 8/11; update workflows for Java 21

---

.github/workflows/package.yml

This pull request updates the `.github/workflows/package.yml` workflow to support both standard and secure Liquibase distributions, improving flexibility and correctness when packaging and releasing artifacts. The changes ensure that the correct distribution is handled throughout the workflow, including download, packaging, uploading, and SDKMAN release steps.
Distribution-specific packaging and release logic:
* The workflow now conditionally downloads and processes either the standard or secure Liquibase zip file based on the `distribution` input, updating filenames and candidate names dynamically. (`.github/workflows/package.yml`)
* All SDKMAN release steps now use the correct candidate name and artifact filename, ensuring accurate metadata for each distribution. …

DAT-20707   DevOps :: Implement Scarf.sh tracking for all Liquibase package distributions

---

.github/workflows/package.yml

This pull request updates the `.github/workflows/package.yml` workflow to improve and standardize the GPG signing process for both regular and dry-run RPM package builds. The changes automate GPG key import, RPM signing, and signature verification, and also update how repository metadata is signed for both production and dry-run environments.
**GPG Key Import and RPM Signing Improvements:**
* Added explicit steps to import the GPG key and sign RPM packages for both dry-run and production workflows using the `crazy-max/ghaction-import-gpg` action, ensuring consistent key handling and signing automation. [[1]](diffhunk://#diff-170ebc8e4dc40acf23cbe0ecce5f3e2aef1652511f59860db704106b197e1d52R296-R333) [[2]](diffhunk://#diff-170ebc8e4dc40acf23cbe0ecce5f3e2aef1652511f59860db704106b197e1d52R376- …

feat: add GPG signing for RPM packages in dry-run and production workflows

---

.github/workflows/package.yml

This pull request updates the `.github/workflows/package.yml` file to improve how Ansible roles are deployed based on the distribution type. The main change is the addition of a new workflow job for the `liquibase-secure` distribution, along with conditional logic to ensure the correct deployment workflow is triggered for each distribution.
Deployment workflow improvements:
* Added a new `upload_secure_ansible_role` job that runs only when the `distribution` input is set to `liquibase-secure`, using the `liquibase-secure-ansible` deployment workflow.
* Updated the existing `upload_ansible_role` job to run only when the `distribution` input is `liquibase`, ensuring the correct workflow is used for each distribution.

DAT-20707  Update ansible calls
